name: Scrape ABC EN

on:
  schedule:
    - cron: "45 * * * *"
  workflow_dispatch: {}

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r workers/requirements.txt
      - run: python workers/scrape_abc_en.py
      - run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "news-bot"
            git config user.email "news-bot@users.noreply.github.com"
            git add abc_en.json abc_en.xml
            git commit -m "chore: update ABC EN feeds"
            git push
          fi
