name: Scrape SBS zh-Hant

on:
  schedule:
    - cron: "15 * * * *"   # 每小時第 15 分鐘跑一次
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r workers/requirements.txt

      - name: Run scraper
        run: python workers/scrape_sbs_zh_hant.py

      - name: Commit and push
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "news-bot"
            git config user.email "news-bot@users.noreply.github.com"
            git add public/sbs_zh_hant.json public/sbs_zh_hant.xml
            git commit -m "Update SBS zh-Hant feed"
            git push
          else
            echo "No changes"
          fi
